#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CatchUp.Droid.Resource", IsApplication=true)]

namespace CatchUp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::CatchUp.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::CatchUp.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::CatchUp.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::CatchUp.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::CatchUp.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::CatchUp.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::CatchUp.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::CatchUp.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::CatchUp.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::CatchUp.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::CatchUp.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::CatchUp.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::CatchUp.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::CatchUp.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::CatchUp.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::CatchUp.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::CatchUp.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::CatchUp.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::CatchUp.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::CatchUp.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::CatchUp.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f04001a
			public const int Send = 2130968602;
			
			// aapt resource value: 0x7f040007
			public const int button1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int button2 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int button3 = 2130968585;
			
			// aapt resource value: 0x7f040017
			public const int checkBox1 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int checkBox2 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int checkBox3 = 2130968601;
			
			// aapt resource value: 0x7f040021
			public const int checkCalendar = 2130968609;
			
			// aapt resource value: 0x7f04001d
			public const int checkLocation = 2130968605;
			
			// aapt resource value: 0x7f04001b
			public const int content = 2130968603;
			
			// aapt resource value: 0x7f04000e
			public const int editText1 = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int editText2 = 2130968595;
			
			// aapt resource value: 0x7f040016
			public const int editText3 = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int imageView1 = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int img_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int linearLayout1 = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int linearLayout2 = 2130968582;
			
			// aapt resource value: 0x7f040014
			public const int linearLayout3 = 2130968596;
			
			// aapt resource value: 0x7f04001c
			public const int requestText = 2130968604;
			
			// aapt resource value: 0x7f040022
			public const int responseText = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int sendResponse = 2130968611;
			
			// aapt resource value: 0x7f04001e
			public const int specLocLayout = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int specLocText = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int specLocTitel = 2130968607;
			
			// aapt resource value: 0x7f04000b
			public const int switch1 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int switch2 = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int textView1 = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int textView2 = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int textView3 = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int textView4 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int textView5 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int textView6 = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int textView7 = 2130968597;
			
			// aapt resource value: 0x7f04000f
			public const int view1 = 2130968591;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Contact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FirstView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Message = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Notification = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Options = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Request = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Response = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SplashScreen = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
